shinyUI(bootstrapPage(
  headerPanel(""),
  div(class = "container",
      div(class = "row",
      div(class = "span6",
          div(class = "row", 
              div(class = "span3",
                  numericInput(inputId = "nLow",
                               label = "Number of low heroes:",
                               value = 0,
                               min = 0,
                               max = NA,
                               step = 1)),
              div(class = "span3",
                  numericInput(inputId = "maxLow", 
                               label = "Total number of low heroes:",
                               value = 7, 
                               min = 0, 
                               max = NA,
                               step = 1))),
          div(class = "row",
              div(class = "span3",
                  numericInput(inputId = "nMed",
                               label = "Number of medium heroes:",
                               value = 0,
                               min = 0,
                               max = NA,
                               step = 1)),
              div(class = "span3", 
                  numericInput(inputId = "maxMed",
                               label = "Total number of medium heroes:",
                               value = 25, 
                               min = 0,
                               max = NA, 
                               step = 1))),
          div(class = "row",
              div(class = "span3",
                  numericInput(inputId = "nHigh",
                               label = "Number of high heroes:",
                               value = 0,
                               min = 0,
                               max = NA,
                               step = 1)),
              div(class = "span3",
                  numericInput(inputId = "maxHigh",
                               label = "Total number of high heroes:",
                               value = 5,
                               min = 0,
                               max = NA, 
                               step = 1)))),
      div(class = "span6",
          textOutput("eV")
      ))
  )
)
)
